# 设置支持最低平台
platform :ios, '8.0'
target 'RobsDrinkingApp' do
# 如果是Swift项目,需添加"use_frameworks!"
    use_frameworks!
# 如果要使用固定版本 可以像下面这么写
# pod 'AFNetworking', '~> 3.2.1'
        pod "AFNetworking"
        pod 'SwiftyJSON', '~>3.1.4'
        pod 'Toast-Swift', '~> 3.0.1'
end
